### ISSUE TITLE
TAGS template not applied on ECS

### ISSUE THREAD

**Issue by KevinGreen** [logdna/logspout#4]
I added the TAGS template following the ECS setup in the README but it doesn't seem to translate the template to a usable tag.

![image](https://user-images.githubusercontent.com/1634785/48382580-7f4c7480-e696-11e8-8b00-dd39697dea15.png)

The syslog logspout adapter does this correctly but the logdna adapter doesn't seem to have this same step: https://github.com/gliderlabs/logspout/blob/0da75a223db992cd5abc836796174588ddfc62b4/adapters/syslog/syslog.go#L134

**Comment by KevinGreen** [comment]
Thanks Samir, the app labels are working well. I've just gotten used to the tags!

**Comment by smusali** [comment]
Hey @KevinGreen,

Sorry for late response!

After working and testing on getting tag from templated string, the newest version has just been released. You can pull it using `latest` or `20181127` tags.

Now tags can be given in the following format: `<simpleTag1>,<simpleTag2>, <templatedTag1>, <simpleTag3>, <templatedTag2>, ...` - inside `<templatedTag` it assumes the outputs are separated with `:`.

While using `handlebars` you should know the structure from which you are trying to pull tags; so, `message` has the following fields:
```
.Data: string,
.Container.Name: string,
.Container.ID: string,
.Container.Config.Image: string,
.Container.Config.Hostname: string,
.Container.Config.Labels: map[string]string,
.Source: string
```

I will update the documentation as soon as possible.

Let me know if you have any other question.

Thanks for using `logdna/logspout`!

**Comment by KevinGreen** [comment]
Thanks Samir, works great!
