### ISSUE TITLE
Timeout from server

### ISSUE THREAD

**Issue by fossejc** [logdna/logspout#7]
Hi all,

I had to restart the Logdna containers on a docker swarm. Since the restart, I get the following output
```
error from client: Post https://logs.logdna.com/logs/ingest?apikey=_____&hostname=logdna_logspout: dial tcp: lookup
 logs.logdna.com on 127.0.0.11:53: read udp 127.0.0.1:33204->127.0.0.11:53: i/o timeout
```

None one of the logs are sent to the Logdna server.

Any idea ?

Thanks for you help

**Comment by smusali** [comment]
@fossejc, sorry for the very late response!

I would recommend you to use [the newest `LogDNA LogSpout v1.2`](https://hub.docker.com/r/logdna/logspout). You can also modify the request timeouts by using `HTTP_CLIENT_TIMEOUT` environment variable if the issue is still happening.
